version: "3.9"

services:
  java_app:
    container_name: product-order-api
    image: hsoaress/product-order-api-img:latest
    restart: always
    env_file:
      - variables.env
    ports:
      - "8080:8080"
    depends_on:
      - java_db

  java_db:
    container_name: postgres-db
    image: postgres:16.1
    restart: always
    env_file:
      - variables.env
    ports:
      - "5432:5432"